export const essay = `Here is the most chilling way I can find of stating the matter. Until recently, “waterboarding” was something that Americans did to other Americans. It was inflicted, and endured, by those members of the Special Forces who underwent the advanced form of training known as SERE (Survival, Evasion, Resistance, Escape). In these harsh exercises, brave men and women were introduced to the sorts of barbarism that they might expect to meet at the hands of a lawless foe who disregarded the Geneva Conventions. But it was something that Americans were being trained to resist, not to inflict.

Exploring this narrow but deep distinction, on a gorgeous day last May I found myself deep in the hill country of western North Carolina, preparing to be surprised by a team of extremely hardened veterans who had confronted their country’s enemies in highly arduous terrain all over the world. They knew about everything from unarmed combat to enhanced interrogation and, in exchange for anonymity, were going to show me as nearly as possible what real waterboarding might be like.

It goes without saying that I knew I could stop the process at any time, and that when it was all over I would be released into happy daylight rather than returned to a darkened cell. But it’s been well said that cowards die many times before their deaths, and it was difficult for me to completely forget the clause in the contract of indemnification that I had signed. This document (written by one who knew) stated revealingly:

“Water boarding” is a potentially dangerous activity in which the participant can receive serious and permanent (physical, emotional and psychological) injuries and even death, including injuries and death due to the respiratory and neurological systems of the body.

As the agreement went on to say, there would be safeguards provided “during the ‘water boarding’ process, however, these measures may fail and even if they work properly they may not prevent Hitchens from experiencing serious injury or death.”

On the night before the encounter I got to sleep with what I thought was creditable ease, but woke early and knew at once that I wasn’t going back to any sort of doze or snooze. The first specialist I had approached with the scheme had asked my age on the telephone and when told what it was (I am 59) had laughed out loud and told me to forget it. Waterboarding is for Green Berets in training, or wiry young jihadists whose teeth can bite through the gristle of an old goat. It’s not for wheezing, paunchy scribblers. For my current “handlers” I had had to produce a doctor’s certificate assuring them that I did not have asthma, but I wondered whether I should tell them about the 15,000 cigarettes I had inhaled every year for the last several decades. I was feeling apprehensive, in other words, and beginning to wish I hadn’t given myself so long to think about it.

I have to be opaque about exactly where I was later that day, but there came a moment when, sitting on a porch outside a remote house at the end of a winding country road, I was very gently yet firmly grabbed from behind, pulled to my feet, pinioned by my wrists (which were then cuffed to a belt), and cut off from the sunlight by having a black hood pulled over my face. I was then turned around a few times, I presume to assist in disorienting me, and led over some crunchy gravel into a darkened room. Well, mainly darkened: there were some oddly spaced bright lights that came as pinpoints through my hood. And some weird music assaulted my ears. (I’m no judge of these things, but I wouldn’t have expected former Special Forces types to be so fond of New Age techno-disco.) The outside world seemed very suddenly very distant indeed.

Arms already lost to me, I wasn’t able to flail as I was pushed onto a sloping board and positioned with my head lower than my heart. (That’s the main point: the angle can be slight or steep.) Then my legs were lashed together so that the board and I were one single and trussed unit. Not to bore you with my phobias, but if I don’t have at least two pillows I wake up with acid reflux and mild sleep apnea, so even a merely supine position makes me uneasy. And, to tell you something I had been keeping from myself as well as from my new experimental friends, I do have a fear of drowning that comes from a bad childhood moment on the Isle of Wight, when I got out of my depth. As a boy reading the climactic torture scene of 1984, where what is in Room 101 is the worst thing in the world, I realize that somewhere in my version of that hideous chamber comes the moment when the wave washes over me. Not that that makes me special: I don’t know anyone who likes the idea of drowning. As mammals we may have originated in the ocean, but water has many ways of reminding us that when we are in it we are out of our element. In brief, when it comes to breathing, give me good old air every time.

You may have read by now the official lie about this treatment, which is that it “simulates” the feeling of drowning. This is not the case. You feel that you are drowning because you are drowning—or, rather, being drowned, albeit slowly and under controlled conditions and at the mercy (or otherwise) of those who are applying the pressure. The “board” is the instrument, not the method. You are not being boarded. You are being watered. This was very rapidly brought home to me when, on top of the hood, which still admitted a few flashes of random and worrying strobe light to my vision, three layers of enveloping towel were added. In this pregnant darkness, head downward, I waited for a while until I abruptly felt a slow cascade of water going up my nose. Determined to resist if only for the honor of my navy ancestors who had so often been in peril on the sea, I held my breath for a while and then had to exhale and—as you might expect—inhale in turn. The inhalation brought the damp cloths tight against my nostrils, as if a huge, wet paw had been suddenly and annihilatingly clamped over my face. Unable to determine whether I was breathing in or out, and flooded more with sheer panic than with mere water, I triggered the pre-arranged signal and felt the unbelievable relief of being pulled upright and having the soaking and stifling layers pulled off me. I find I don’t want to tell you how little time I lasted.

WATERBOARDING IS FOR GREEN BERETS IN TRAINING. IT’S NOT FOR WHEEZING, PAUNCHY SCRIBBLERS.
This is because I had read that Khalid Sheikh Mohammed, invariably referred to as the “mastermind” of the atrocities of September 11, 2001, had impressed his interrogators by holding out for upwards of two minutes before cracking. (By the way, this story is not confirmed. My North Carolina friends jeered at it. “Hell,” said one, “from what I heard they only washed his damn face before he babbled.”) But, hell, I thought in my turn, no Hitchens is going to do worse than that. Well, O.K., I admit I didn’t outdo him. And so then I said, with slightly more bravado than was justified, that I’d like to try it one more time. There was a paramedic present who checked my racing pulse and warned me about adrenaline rush. An interval was ordered, and then I felt the mask come down again. Steeling myself to remember what it had been like last time, and to learn from the previous panic attack, I fought down the first, and some of the second, wave of nausea and terror but soon found that I was an abject prisoner of my gag reflex. The interrogators would hardly have had time to ask me any questions, and I knew that I would quite readily have agreed to supply any answer. I still feel ashamed when I think about it. Also, in case it’s of interest, I have since woken up trying to push the bedcovers off my face, and if I do anything that makes me short of breath I find myself clawing at the air with a horrible sensation of smothering and claustrophobia. No doubt this will pass. As if detecting my misery and shame, one of my interrogators comfortingly said, “Any time is a long time when you’re breathing water.” I could have hugged him for saying so, and just then I was hit with a ghastly sense of the sadomasochistic dimension that underlies the relationship between the torturer and the tortured. I apply the Abraham Lincoln test for moral casuistry: “If slavery is not wrong, nothing is wrong.” Well, then, if waterboarding does not constitute torture, then there is no such thing as torture.


7273 View article pages

I am somewhat proud of my ability to “keep my head,” as the saying goes, and to maintain presence of mind under trying circumstances. I was completely convinced that, when the water pressure had become intolerable, I had firmly uttered the pre-determined code word that would cause it to cease. But my interrogator told me that, rather to his surprise, I had not spoken a word. I had activated the “dead man’s handle” that signaled the onset of unconsciousness. So now I have to wonder about the role of false memory and delusion. What I do recall clearly, though, is a hard finger feeling for my solar plexus as the water was being poured. What was that for? “That’s to find out if you are trying to cheat, and timing your breathing to the doses. If you try that, we can outsmart you. We have all kinds of enhancements.” I was briefly embarrassed that I hadn’t earned or warranted these refinements, but it hit me yet again that this is certainly the language of torture.

IF WATERBOARDING DOES NOT CONSTITUTE TORTURE, THEN THERE IS NO SUCH THING AS TORTURE.
Maybe I am being premature in phrasing it thus. Among the SERE veterans there are at least two views on all this, which means in practice that there are two opinions on whether or not “waterboarding” constitutes torture. I have had some extremely serious conversations on the topic, with two groups of highly decent and serious men, and I think that both cases have to be stated at their strongest.

The team who agreed to give me a hard time in the woods of North Carolina belong to a highly honorable group. This group regards itself as out on the front line in defense of a society that is too spoiled and too ungrateful to appreciate those solid, underpaid volunteers who guard us while we sleep. These heroes stay on the ramparts at all hours and in all weather, and if they make a mistake they may be arraigned in order to scratch some domestic political itch. Faced with appalling enemies who make horror videos of torture and beheadings, they feel that they are the ones who confront denunciation in our press, and possible prosecution. As they have just tried to demonstrate to me, a man who has been waterboarded may well emerge from the experience a bit shaky, but he is in a mood to surrender the relevant information and is unmarked and undamaged and indeed ready for another bout in quite a short time. When contrasted to actual torture, waterboarding is more like foreplay. No thumbscrew, no pincers, no electrodes, no rack. Can one say this of those who have been captured by the tormentors and murderers of (say) Daniel Pearl? On this analysis, any call to indict the United States for torture is therefore a lame and diseased attempt to arrive at a moral equivalence between those who defend civilization and those who exploit its freedoms to hollow it out, and ultimately to bring it down. I myself do not trust anybody who does not clearly understand this viewpoint.

Against it, however, I call as my main witness Mr. Malcolm Nance. Mr. Nance is not what you call a bleeding heart. In fact, speaking of the coronary area, he has said that, in battlefield conditions, he “would personally cut bin Laden’s heart out with a plastic M.R.E. spoon.” He was to the fore on September 11, 2001, dealing with the burning nightmare in the debris of the Pentagon. He has been involved with the SERE program since 1997. He speaks Arabic and has been on al-Qaeda’s tail since the early 1990s. His most recent book, The Terrorists of Iraq, is a highly potent analysis both of the jihadist threat in Mesopotamia and of the ways in which we have made its life easier. I passed one of the most dramatic evenings of my life listening to his cold but enraged denunciation of the adoption of waterboarding by the United States. The argument goes like this:

1. Waterboarding is a deliberate torture technique and has been prosecuted as such by our judicial arm when perpetrated by others.

2. If we allow it and justify it, we cannot complain if it is employed in the future by other regimes on captive U.S. citizens. It is a method of putting American prisoners in harm’s way.

3. It may be a means of extracting information, but it is also a means of extracting junk information. (Mr. Nance told me that he had heard of someone’s being compelled to confess that he was a hermaphrodite. I later had an awful twinge while wondering if I myself could have been “dunked” this far.) To put it briefly, even the C.I.A. sources for the Washington Post story on waterboarding conceded that the information they got out of Khalid Sheikh Mohammed was “not all of it reliable.” Just put a pencil line under that last phrase, or commit it to memory.

4. It opens a door that cannot be closed. Once you have posed the notorious “ticking bomb” question, and once you assume that you are in the right, what will you not do? Waterboarding not getting results fast enough? The terrorist’s clock still ticking? Well, then, bring on the thumbscrews and the pincers and the electrodes and the rack.

Masked by these arguments, there lurks another very penetrating point. Nance doubts very much that Khalid Sheikh Mohammed lasted that long under the water treatment (and I am pathetically pleased to hear it). It’s also quite thinkable, if he did, that he was trying to attain martyrdom at our hands. But even if he endured so long, and since the United States has in any case bragged that in fact he did, one of our worst enemies has now become one of the founders of something that will someday disturb your sleep as well as mine. To quote Nance:

Torture advocates hide behind the argument that an open discussion about specific American interrogation techniques will aid the enemy. Yet, convicted A1 Qaeda members and innocent captives who were released to their host nations have already debriefed the world through hundreds of interviews, movies and documentaries on exactly what methods they were subjected to and how they endured. Our own missteps have created a cadre of highly experienced lecturers for Al Qaeda’s own virtual SERE school for terrorists.

Which returns us to my starting point, about the distinction between training for something and training to resist it. One used to be told—and surely with truth—that the lethal fanatics of al-Qaeda were schooled to lie, and instructed to claim that they had been tortured and maltreated whether they had been tortured and maltreated or not. Did we notice what a frontier we had crossed when we admitted and even proclaimed that their stories might in fact be true? I had only a very slight encounter on that frontier, but I still wish that my experience were the only way in which the words “waterboard” and “American” could be mentioned in the same (gasping and sobbing) breath. I never knew I could be an engineer. An engineer is a very important role. I love being an engineer.`